### ISSUE TITLE
win32 build error

### ISSUE THREAD

**Issue by codz01** [Coldzer0/ImGui-Pascal#1]
Hi
i tried to build the demo with fpc & lazarus for windows 32bits , i got these errors 
![error](https://github.com/Coldzer0/ImGui-Pascal/assets/10813427/f40a4470-99ca-49a0-9ca7-5ba9d08f4b92)

**Comment by Coldzer0** [comment]
I didn't upload any 32-bit libraries; I only uploaded 64-bit.
I'll compile SDL2 and ImGui to 32bit and upload it as soon as possible.

**Comment by Coldzer0** [comment]
@codz01 

I updated the project; I was working on a complete rework for the APIs and other fixes and additions like ImPlot.
And the code now supports 32bit on Windows.

Test it and give me your feed back if it works or if there's any problem.

**Comment by codz01** [comment]
thank you , it works now , looks amazing 
do you know why the size of the application is 5mb even its compiled with release mode

**Comment by Coldzer0** [comment]
> thank you , it works now , looks amazing 
> 
> do you know why the size of the application is 5mb even its compiled with release mode 


That's because the static linking and the file has no dependencies.

You can disable that by editing `src/ImGuiPasDef.inc` 
You will see the comment inside.


But this will make it use the external dlls.


When I will implement the win32 backend it will be smaller on windows because then we won't use the SDL2 library at all.

And for cimgui library I think I'll compile another version without the demo code window they have, this will make the final output a lot smaller.
